version: '3.1'

services:

  db:
    image: mysql:8.4
    container_name: mysql
    command: mysqld --mysql-native-password=ON
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password